In [2]:
import pandas as pd
import csv
import re

In [3]:
user_name = input("User Name: ")
directory1 = "C:\\Users\\"
directory2 = "\\Desktop\\Payroll System"
directory = directory1 + user_name + directory2

User Name: ASUS

In [4]:
#Looks at all Out-Day.csv's to combine into a single week statistic
folder_name = str(input("Name of Folder: "))
out_folder_name = "Out-" + folder_name

monday_file = str(input("Monday of the week: "))
tuesday_file = str(input("Tuesday of the week: "))
wednesday_file = str(input("Wednesday of the week: "))
thursday_file = str(input("Thursday of the week: "))
friday_file = str(input("Friday of the week: "))
saturday_file = str(input("Saturday of the week: "))
sunday_file = str(input("Sunday of the week: "))


out_directory_folder_monday = directory + "\\" + folder_name + "\\" + out_folder_name + "\\Out-" + monday_file+ ".csv"
out_directory_folder_tueday = directory + "\\" + folder_name + "\\" + out_folder_name + "\\Out-" + tuesday_file + ".csv"
out_directory_folder_wednesday = directory + "\\" + folder_name + "\\" + out_folder_name + "\\Out-" + wednesday_file + ".csv"
out_directory_folder_thursday = directory + "\\" + folder_name + "\\" + out_folder_name + "\\Out-" + thursday_file + ".csv"
out_directory_folder_friday = directory + "\\" + folder_name + "\\" + out_folder_name + "\\Out-" + friday_file+ ".csv"
out_directory_folder_saturday = directory + "\\" + folder_name + "\\" + out_folder_name + "\\Out-" + saturday_file + ".csv"
out_directory_folder_sunday = directory + "\\" + folder_name + "\\" + out_folder_name + "\\Out-" + sunday_file + ".csv"

Monday_df = pd.read_csv(out_directory_folder_monday)
Tuesday_df = pd.read_csv(out_directory_folder_tueday)
Wednesday_df = pd.read_csv(out_directory_folder_wednesday)
Thursday_df = pd.read_csv(out_directory_folder_thursday)
Friday_df = pd.read_csv(out_directory_folder_friday)
Saturday_df = pd.read_csv(out_directory_folder_saturday)
Sunday_df = pd.read_csv(out_directory_folder_sunday)

Name of Folder: July 22-28
Monday of the week: July 22
Tuesday of the week: July 23
Wednesday of the week: July 24
Thursday of the week: July 25
Friday of the week: July 26
Saturday of the week: July 27
Sunday of the week: July 28

In [9]:
Employee_Info_W_Tax_df = pd.read_csv(directory + '\\1 Information CSVs\\Employee-Information-With-Tax.csv')

ID_to_Rates_df = Employee_Info_W_Tax_df.loc[:,"ID Number":"Rate Per Month"]
Tax_Info_df = Employee_Info_W_Tax_df.loc[:,"Income Tax":"SSS Employer Contribution Day"]
Tax_Info_df['ID Number'] = Employee_Info_W_Tax_df.loc[:,"ID Number"]

Business_Hours_df = pd.read_csv(directory + '\\4 Reference CSVs\\One Week Statistic Reference.csv')

Summary_Statistic_df = pd.merge(ID_to_Rates_df,Business_Hours_df,how='left')
Summary_Statistic_df = pd.merge(Summary_Statistic_df,Tax_Info_df,on='ID Number',how='left')

In [10]:
#Basic Business Hours, Deductibes, and Bonus
Summary_Statistic_df.loc[:,"Total Work Hours"] = Monday_df.loc[:,"Work Hours"] + Tuesday_df.loc[:,"Work Hours"] + Wednesday_df.loc[:,"Work Hours"] + Thursday_df.loc[:,"Work Hours"] + Friday_df.loc[:,"Work Hours"] + Saturday_df.loc[:,"Work Hours"] + Sunday_df.loc[:,"Work Hours"] 
Summary_Statistic_df.loc[:,"Total Basic Salary"] = Monday_df.loc[:,"Basic Salary"] + Tuesday_df.loc[:,"Basic Salary"] + Wednesday_df.loc[:,"Basic Salary"] + Thursday_df.loc[:,"Basic Salary"] + Friday_df.loc[:,"Basic Salary"] + Saturday_df.loc[:,"Basic Salary"] + Sunday_df.loc[:,"Basic Salary"] 
Summary_Statistic_df.loc[:,"Total Overtime Hours"] = Monday_df.loc[:,"Overtime Hours"] + Tuesday_df.loc[:,"Overtime Hours"] + Wednesday_df.loc[:,"Overtime Hours"] + Thursday_df.loc[:,"Overtime Hours"] + Friday_df.loc[:,"Overtime Hours"] + Saturday_df.loc[:,"Overtime Hours"] + Sunday_df.loc[:,"Overtime Hours"]
Summary_Statistic_df.loc[:,"Total Overtime Pay"] = Monday_df.loc[:,"Overtime Pay"] + Tuesday_df.loc[:,"Overtime Pay"] + Wednesday_df.loc[:,"Overtime Pay"] + Thursday_df.loc[:,"Overtime Pay"] + Friday_df.loc[:,"Overtime Pay"] + Saturday_df.loc[:,"Overtime Pay"] + Sunday_df.loc[:,"Overtime Pay"]
Summary_Statistic_df.loc[:,"Total Late Hours"] = Monday_df.loc[:,"Late Hours"] + Tuesday_df.loc[:,"Late Hours"] + Wednesday_df.loc[:,"Late Hours"] + Thursday_df.loc[:,"Late Hours"] + Friday_df.loc[:,"Late Hours"] + Saturday_df.loc[:,"Late Hours"] + Sunday_df.loc[:,"Late Hours"]
Summary_Statistic_df.loc[:,"Total Late Deduction"] = Monday_df.loc[:,"Late Deductions"] + Tuesday_df.loc[:,"Late Deductions"] + Wednesday_df.loc[:,"Late Deductions"] + Thursday_df.loc[:,"Late Deductions"] + Friday_df.loc[:,"Late Deductions"] + Saturday_df.loc[:,"Late Deductions"] + Sunday_df.loc[:,"Late Deductions"]
Summary_Statistic_df.loc[:,"Total Gross Salary"] = Monday_df.loc[:,"Gross Salary"] + Tuesday_df.loc[:,"Gross Salary"] + Wednesday_df.loc[:,"Gross Salary"] + Thursday_df.loc[:,"Gross Salary"] + Friday_df.loc[:,"Gross Salary"] + Saturday_df.loc[:,"Gross Salary"] + Sunday_df.loc[:,"Gross Salary"]
Summary_Statistic_df.loc[:,"Total Debt"] = Monday_df.loc[:,"Debt"] + Tuesday_df.loc[:,"Debt"] + Wednesday_df.loc[:,"Debt"] + Thursday_df.loc[:,"Debt"] + Friday_df.loc[:,"Debt"] + Saturday_df.loc[:,"Debt"] + Sunday_df.loc[:,"Debt"]
Summary_Statistic_df.loc[:,"Total Deductibles"] = Monday_df.loc[:,"Deductibles"] + Tuesday_df.loc[:,"Deductibles"] + Wednesday_df.loc[:,"Deductibles"] + Thursday_df.loc[:,"Deductibles"] + Friday_df.loc[:,"Deductibles"] + Saturday_df.loc[:,"Deductibles"] + Sunday_df.loc[:,"Deductibles"]
Summary_Statistic_df.loc[:,"Total Bonus"] = Monday_df.loc[:,"Bonus"] + Tuesday_df.loc[:,"Bonus"] + Wednesday_df.loc[:,"Bonus"] + Thursday_df.loc[:,"Bonus"] + Friday_df.loc[:,"Bonus"] + Saturday_df.loc[:,"Bonus"] + Sunday_df.loc[:,"Bonus"]
Summary_Statistic_df.loc[:,"Total Standing Salary"] = Monday_df.loc[:,"Standing Salary"] + Tuesday_df.loc[:,"Standing Salary"] + Wednesday_df.loc[:,"Standing Salary"] + Thursday_df.loc[:,"Standing Salary"] + Friday_df.loc[:,"Standing Salary"] + Saturday_df.loc[:,"Standing Salary"] + Sunday_df.loc[:,"Standing Salary"]

#Taxes per week
Summary_Statistic_df.loc[:,"Total Income Tax"] = Summary_Statistic_df.loc[:,"Income Tax Day"] * 7
Summary_Statistic_df.loc[:,"Total Philhealth"] = Summary_Statistic_df.loc[:,"Philhealth Day"] * 7
Summary_Statistic_df.loc[:,"Total Pagibig"] = Summary_Statistic_df.loc[:,"Pagibig Day"] * 7
Summary_Statistic_df.loc[:,"Total SSS Employee Contribution"] = Summary_Statistic_df.loc[:,"SSS Employee Contribution Day"] * 7
Summary_Statistic_df.loc[:,"Total SSS Employer Contribution"] = Summary_Statistic_df.loc[:,"SSS Employer Contribution Day"] * 7

#Final Total Salary
Summary_Statistic_df.loc[:,"Salary for the Week"] = (Summary_Statistic_df.loc[:,"Total Standing Salary"] - (Summary_Statistic_df.loc[:,"Total Income Tax"] + Summary_Statistic_df.loc[:,"Total Philhealth"] + Summary_Statistic_df.loc[:,"Total Pagibig"] + Summary_Statistic_df.loc[:,"Total SSS Employee Contribution"])).round(2)

In [25]:
Summary_Statistic_df

,ID Number,First,Last,Date Started,Date Left,Rate Per Day,Rate Per Month,Total Work Hours,Total Basic Salary,Total Overtime Hours,...,Philhealth Day,Pagibig Day,SSS Employee Contribution Day,SSS Employer Contribution Day,Total Income Tax,Total Philhealth,Total Pagibig,Total SSS Employee Contribution,Total SSS Employer Contribution,Salary for the Week
0,10000000,Angelo,Johnson,12/06/2018,0,537,16110,56,3759.0,0,...,7.38,1.07,21.33,43.67,0.00,51.66,7.49,149.31,305.69,3483.42
1,10000001,Bea,Ramirez,30/07/2015,0,600,18000,60,4200.0,4,...,8.25,1.20,24.00,49.00,0.00,57.75,8.40,168.00,343.00,3435.85
2,10000002,Chris,Evans,22/12/2018,0,840,25200,60,5880.0,4,...,11.55,1.68,26.67,54.33,152.81,80.85,11.76,186.69,380.31,5238.89
3,10000003,Dennis,Tan,04/12/2016,0,550,16500,65,3850.0,9,...,7.56,1.10,22.00,45.00,0.00,52.92,7.70,154.00,315.00,4326.01
4,10000004,Emily,Santos,14/08/2017,0,1045,31350,62,7315.0,6,...,14.37,2.09,26.67,54.33,368.06,100.59,14.63,186.69,380.31,6821.41
5,10000005,Frances,Mercado,15/03/2019,0,729,21870,58,5103.0,2,...,10.02,1.46,26.67,54.33,36.26,70.14,10.22,186.69,380.31,4179.49
6,10000006,Gary,Cruz,21/03/2016,0,1255,37650,63,8785.0,7,...,17.26,2.51,26.67,54.33,638.96,120.82,17.57,186.69,380.31,8456.54
7,10000007,Hans,Chan,16/05/2018,0,920,27600,58,6440.0,2,...,12.65,1.84,26.67,54.33,236.81,88.55,12.88,186.69,380.31,4324.07
8,10000008,Isabel,Juan,18/05/2017,0,620,18600,59,4340.0,3,...,8.52,1.24,24.67,50.33,0.00,59.64,8.68,172.69,352.31,3226.24
9,10000009,Jen,Ang,12/09/2018,0,845,25350,63,5915.0,7,...,11.62,1.69,26.67,54.33,158.06,81.34,11.83,186.69,380.31,4812.01

In [11]:
summary_statistic_name = input("Name of one week Statistic: ")
directory_folder = directory + "\\" + folder_name + "\\" + summary_statistic_name + ".csv"

Output_csv = Summary_Statistic_df.to_csv(directory_folder)

Name of one week Statistic: OWS for July 22-29