In [1]:
import pandas as pd
import html

In [2]:
user_name = input("User Name: ")
directory1 = "C:\\Users\\"
directory2 = "\\Desktop\\Payroll System"
directory = directory1 + user_name + directory2

User Name: ASUS

In [4]:
folder_name = str(input("Name of Folder: "))
one_week_statistic_name = input("Write the name of the one week statistic: ")
directory_folder_statname = directory + "\\" + folder_name + "\\" + one_week_statistic_name + ".csv"

one_week_statistic_df = pd.read_csv(directory_folder_statname)
OWStransposed = one_week_statistic_df.transpose()
ows_dict = OWStransposed.to_dict('series')

OWStransposed

Name of Folder: July 22-28
Write the name of the one week statistic: OWS for July 22-28

,0,1,2,3,4,5,6,7,8,9
Unnamed: 0,0,1,2,3,4,5,6,7,8,9
ID Number,10000000,10000001,10000002,10000003,10000004,10000005,10000006,10000007,10000008,10000009
First,Angelo,Bea,Chris,Dennis,Emily,Frances,Gary,Hans,Isabel,Jen
Last,Johnson,Ramirez,Evans,Tan,Santos,Mercado,Cruz,Chan,Juan,Ang
Date Started,12/06/2018,30/07/2015,22/12/2018,04/12/2016,14/08/2017,15/03/2019,21/03/2016,16/05/2018,18/05/2017,12/09/2018
Date Left,0,0,0,0,0,0,0,0,0,0
Rate Per Day,537,600,840,550,1045,729,1255,920,620,845
Rate Per Month,16110,18000,25200,16500,31350,21870,37650,27600,18600,25350
Total Work Hours,56,60,60,65,62,58,63,58,59,63
Total Basic Salary,3759,4200,5880,3850,7315,5103,8785,6440,4340,5915
Total Overtime Hours,0,4,4,9,6,2,7,2,3,7
Total Overtime Pay,0,390,546,804.38,1018.86,236.92,1427.58,299,302.25,961.17
Total Late Hours,1,2,3,1,4,1,0,4,6,2
Total Late Deduction,67.12,150,315,68.75,522.48,91.12,0,460,465,211.24
Total Gross Salary,3691.88,4440,6111,4585.63,7811.38,5248.8,10212.6,6279,4177.25,6664.93
Total Debt,0,170,50,0,210,171,112,890,350,770
Total Deductibles,0,600,390,45,110,595,680,540,360,645
Total Bonus,0,0,0,0,0,0,0,0,0,0
Total Standing Salary,3691.88,3670,5671,4540.63,7491.38,4482.8,9420.58,4849,3467.25,5249.93
Income Tax,0,0,655,0,1577.5,155.5,2738.33,1015,0,677.5
Philhealth,221.51,247.5,346.5,226.88,431.06,300.71,517.69,379.5,255.75,348.56
Pagibig,32.22,36,50.4,33,62.7,43.74,75.3,55.2,37.2,50.7
SSS Employee Contribution,640,720,800,660,800,800,800,800,740,800
SSS Employer Contribution,1310,1470,1630,1350,1630,1630,1630,1630,1510,1630
Income Tax Day,0,0,21.83,0,52.58,5.18,91.28,33.83,0,22.58
Philhealth Day,7.38,8.25,11.55,7.56,14.37,10.02,17.26,12.65,8.52,11.62
Pagibig Day,1.07,1.2,1.68,1.1,2.09,1.46,2.51,1.84,1.24,1.69
SSS Employee Contribution Day,21.33,24,26.67,22,26.67,26.67,26.67,26.67,24.67,26.67
SSS Employer Contribution Day,43.67,49,54.33,45,54.33,54.33,54.33,54.33,50.33,54.33
Total Income Tax,0,0,152.81,0,368.06,36.26,638.96,236.81,0,158.06
Total Philhealth,51.66,57.75,80.85,52.92,100.59,70.14,120.82,88.55,59.64,81.34
Total Pagibig,7.49,8.4,11.76,7.7,14.63,10.22,17.57,12.88,8.68,11.83
Total SSS Employee Contribution,149.31,168,186.69,154,186.69,186.69,186.69,186.69,172.69,186.69
Total SSS Employer Contribution,305.69,343,380.31,315,380.31,380.31,380.31,380.31,352.31,380.31
Salary for the Week,3483.42,3435.85,5238.89,4326.01,6821.41,4179.49,8456.54,4324.07,3226.24,4812.01

In [5]:
main_html = """

<html>
    <head>
        <title>Pay Slip for {0} {1} </title>
    </head>
    <body>
    
<p><strong>Employee Payroll</strong>
<br />-----------------------------------------------------------------------------------------<br />
Name: {0} {1} <br />
ID Number: {2} <br />
Date Started: {3}<br />
Rate Per Day: {4}<br />
Rate Per Month: {5}</p>

<p>Total Work Hours: {6}<br />
Overtime Hours: {7}<br />
Late Hours: {8}
<br />------------------------------------------------------------------------------------------<br />
Basic Salary:............................................{9}<br />
Overtime Pay:..........................................{10}<br />
Late Deduction:........................................{11}<br />
Total Gross Salary:...................................{12} <br />
Total Debt:................................................{13}<br />
Deductibles:.............................................{14}<br />
Bonuses:..................................................{15}</p>

<p><strong>Standing Salary:</strong>.........................................<strong>{16}<br />
</strong>-------------------------------------------------------------------------------------------<br />
Income Tax:..............................................{17}<br />
Philhealth:.................................................{18}<br />
Pagibig:.....................................................{19}<br />
SSS Employee Contribution:....................{20}<br />
SSS Employer Contribution:.....................{21}</p>
<p><strong>Salary of the Week:.................................{22} </strong></p>

    </body>
</html>
"""

In [6]:
for i in ows_dict:
    final_html = main_html.format(
        ows_dict[i]['First'],
        ows_dict[i]['Last'],
        ows_dict[i]['ID Number'],
        ows_dict[i]['Date Started'],
        ows_dict[i]['Rate Per Day'],
        ows_dict[i]['Rate Per Month'],
        ows_dict[i]['Total Work Hours'],
        ows_dict[i]['Total Overtime Hours'],
        ows_dict[i]['Total Late Hours'],
        ows_dict[i]['Total Basic Salary'],
        ows_dict[i]['Total Overtime Pay'],
        ows_dict[i]['Total Late Deduction'],
        ows_dict[i]['Total Gross Salary'],
        ows_dict[i]['Total Debt'],
        ows_dict[i]['Total Deductibles'],
        ows_dict[i]['Total Bonus'],
        ows_dict[i]['Total Standing Salary'],
        ows_dict[i]['Total Income Tax'],
        ows_dict[i]['Total Philhealth'],
        ows_dict[i]['Total Pagibig'],
        ows_dict[i]['Total SSS Employee Contribution'],
        ows_dict[i]['Total SSS Employer Contribution'],
        ows_dict[i]['Salary for the Week'])
    first_name = ows_dict[i]['First']
    last_name = ows_dict[i]['Last']
    pay_slip_name = directory + "\\" + folder_name + "\\" + "html-" + folder_name + "\\" + "Pay Slip for"+ " " + first_name + " "+ last_name + ".html"
    with open(pay_slip_name, "w") as file:
        file.write(final_html)