In [17]:
import pandas as pd
import csv

In [18]:
user_name = input("User Name: ")
directory1 = "/Users/"
directory2 = "/Desktop/Payroll System"
directory = directory1 + user_name + directory2

User Name: ASUS

In [5]:
Employee_Info_W_Tax_df = pd.read_csv(directory + '/1 Information CSVs/Employee-Information.csv')
Philhealth_df = pd.read_csv(directory + '/2 Tax Information/Philhealth.csv')
Pagibig_df = pd.read_csv(directory + '/2 Tax Information/Pagibig.csv')
SSS_df = pd.read_csv(directory + '/2 Tax Information/SSS.csv')

Employee_Info_W_Tax_df.loc[:,'Rate Per Month'] = Employee_Info_W_Tax_df.loc[:,'Rate Per Month'].apply(pd.to_numeric)
Employee_Info_W_Tax_df.dtypes

ID Number          int64
First             object
Last              object
Date Started      object
Date Left          int64
Rate Per Day       int64
Rate Per Month     int64
dtype: object

In [6]:
def IncomeTax(x):
    if x <= 250000/12:
        IncomeTax = 0
    elif x > 250000/12 and x <= 400000/12:
        IncomeTax = (x-250000/12)*0.15
    elif x > 400000/12 and x <= 800000:
        IncomeTax = 22500/12 + (x-400000/12)*0.20
    elif x > 800000/12 and x <= 2000000/12:
        IncomeTax = 102500/12 + (x-800000/12)*0.25
    elif x > 2000000/12 and x <= 8000000/12:
        IncomeTax = 402500/12 + (x-2000000/12)*0.30
    else:
        IncomeTax = 2202500/12 + (x-8000000/12)*0.35
    return IncomeTax

In [7]:
def Philhealth(x):
    if x <= 10000:
        Philhealth = 137.5
    elif x > 10000 and x <= 39999.99:
        Philhealth = x*0.0275/2
    else:
        Philhealth = 550
    return Philhealth

In [8]:
def Pagibig(x):
    if x <= 1500:
        Pagibig = x*0.001
    else:
        Pagibig = x*0.002
    return Pagibig

In [9]:
# Dictionary Version for csv
import csv
with open(directory + '/2 Tax Information/SSS.csv',newline="") as csv_file:
    SSS = csv.DictReader(csv_file)
    SSS_csv = []
    for i in SSS:
        Bottom_value_of_Range = i['Bottom value of Range']
        Highest_value_of_range = i['Highest value of range']
        Monthly_Salary_Credit = i['Monthly Salary Credit']
        Employee_Contribution = i['Employee Contribution']
        Employer_Contribution = i['Employer Contribution']
        SSS_csv.append([Bottom_value_of_Range,Highest_value_of_range,Monthly_Salary_Credit,Employee_Contribution,Employer_Contribution])

In [10]:
SSS_csv.pop()

['19750', 'AND ABOVE', '20000', '800', '1630']

In [11]:
#SSS without "AND ABOVE"
SSS_csv

[['0', '2249.99', '2000', '80', '170'],
 ['2250', '2749.99', '2500', '100', '210'],
 ['2750', '3249.99', '3000', '120', '250'],
 ['3250', '3749.99', '3500', '140', '290'],
 ['3750', '4249.99', '4000', '160', '330'],
 ['4250', '4749.99', '4500', '180', '370'],
 ['4750', '5249.99', '5000', '200', '410'],
 ['5250', '5749.99', '5500', '220', '450'],
 ['5750', '6249.99', '6000', '240', '490'],
 ['6250', '6749.99', '6500', '260', '530'],
 ['6750', '7249.99', '7000', '280', '570'],
 ['7250', '7749.99', '7500', '300', '610'],
 ['7750', '8249.99', '8000', '320', '650'],
 ['8250', '8749.99', '8500', '340', '690'],
 ['8750', '9249.99', '9000', '360', '730'],
 ['9250', '9749.99', '9500', '380', '770'],
 ['9750', '10249.99', '10000', '400', '810'],
 ['10250', '10749.99', '10500', '420', '850'],
 ['10750', '11249.99', '11000', '440', '890'],
 ['11250', '11749.99', '11500', '460', '930'],
 ['11750', '12249.99', '12000', '480', '970'],
 ['12250', '12749.99', '12500', '500', '1010'],
 ['12750', '13249.99', '13000', '520', '1050'],
 ['13250', '13749.99', '13500', '540', '1090'],
 ['13750', '14249.99', '14000', '560', '1130'],
 ['14250', '14749.99', '14500', '580', '1170'],
 ['14750', '15249.99', '15000', '600', '1230'],
 ['15250', '15749.99', '15500', '620', '1270'],
 ['15750', '16249.99', '16000', '640', '1310'],
 ['16250', '16749.99', '16500', '660', '1350'],
 ['16750', '17249.99', '17000', '680', '1390'],
 ['17250', '17749.99', '17500', '700', '1430'],
 ['17750', '18249.99', '18000', '720', '1470'],
 ['18250', '18749.99', '18500', '740', '1510'],
 ['18750', '19249.99', '19000', '760', '1550'],
 ['19250', '19749.99', '19500', '780', '1590']]

In [12]:
import csv
with open(directory + '/2 Tax Information/SSS.csv',newline="") as csv_file:
    SSS = csv.DictReader(csv_file)
    
    def SSS_Employee_Contribution(x):
        Contribution = 0
        if x > 19750:
            Contribution = 800
        for i in SSS_csv:
            if x > float(i[0]) and x < float(i[1]):
                Contribution = int(i[3])
        return Contribution
    
    def SSS_Employer_Contribution(x):
        Contribution = 0
        for i in SSS_csv:
            if x > 19750:
                Contribution = 1630
            if x > float(i[0]) and x < float(i[1]):
                Contribution = int(i[4])
        return Contribution

    #Monthly Taxes
    Employee_Info_W_Tax_df.loc[:,'Income Tax'] = Employee_Info_W_Tax_df.loc[:,'Rate Per Month'].apply(lambda x: IncomeTax(x)).round(2)
    Employee_Info_W_Tax_df.loc[:,'Philhealth'] = Employee_Info_W_Tax_df.loc[:,'Rate Per Month'].apply(lambda x: Philhealth(x)).round(2)
    Employee_Info_W_Tax_df.loc[:,'Pagibig'] = Employee_Info_W_Tax_df.loc[:,'Rate Per Month'].apply(lambda x: Pagibig(x)).round(2)
    Employee_Info_W_Tax_df.loc[:,'SSS Employee Contribution'] = Employee_Info_W_Tax_df.loc[:,'Rate Per Month'].apply(lambda x: SSS_Employee_Contribution(x))
    Employee_Info_W_Tax_df.loc[:,'SSS Employer Contribution'] = Employee_Info_W_Tax_df.loc[:,'Rate Per Month'].apply(lambda x: SSS_Employer_Contribution(x))
    
    #Daily Taxes
    Employee_Info_W_Tax_df['Income Tax Day'] = (Employee_Info_W_Tax_df.loc[:,'Income Tax']*1/30).round(2)
    Employee_Info_W_Tax_df['Philhealth Day'] = (Employee_Info_W_Tax_df.loc[:,'Philhealth']*1/30).round(2)
    Employee_Info_W_Tax_df['Pagibig Day'] = (Employee_Info_W_Tax_df.loc[:,'Pagibig']*1/30).round(2)
    Employee_Info_W_Tax_df['SSS Employee Contribution Day'] = (Employee_Info_W_Tax_df.loc[:,'SSS Employee Contribution']/30).round(2)
    Employee_Info_W_Tax_df['SSS Employer Contribution Day'] = (Employee_Info_W_Tax_df.loc[:,'SSS Employer Contribution']/30).round(2)

In [13]:
Employee_Info_W_Tax_df

,ID Number,First,Last,Date Started,Date Left,Rate Per Day,Rate Per Month,Income Tax,Philhealth,Pagibig,SSS Employee Contribution,SSS Employer Contribution,Income Tax Day,Philhealth Day,Pagibig Day,SSS Employee Contribution Day,SSS Employer Contribution Day
0,10000000,Angelo,Johnson,12/06/2018,0,537,16110,0.00,221.51,32.22,640,1310,0.00,7.38,1.07,21.33,43.67
1,10000001,Bea,Ramirez,30/07/2015,0,600,18000,0.00,247.50,36.00,720,1470,0.00,8.25,1.20,24.00,49.00
2,10000002,Chris,Evans,22/12/2018,0,840,25200,655.00,346.50,50.40,800,1630,21.83,11.55,1.68,26.67,54.33
3,10000003,Dennis,Tan,04/12/2016,0,550,16500,0.00,226.88,33.00,660,1350,0.00,7.56,1.10,22.00,45.00
4,10000004,Emily,Santos,14/08/2017,0,1045,31350,1577.50,431.06,62.70,800,1630,52.58,14.37,2.09,26.67,54.33
5,10000005,Frances,Mercado,15/03/2019,0,729,21870,155.50,300.71,43.74,800,1630,5.18,10.02,1.46,26.67,54.33
6,10000006,Gary,Cruz,21/03/2016,0,1255,37650,2738.33,517.69,75.30,800,1630,91.28,17.26,2.51,26.67,54.33
7,10000007,Hans,Chan,16/05/2018,0,920,27600,1015.00,379.50,55.20,800,1630,33.83,12.65,1.84,26.67,54.33
8,10000008,Isabel,Juan,18/05/2017,0,620,18600,0.00,255.75,37.20,740,1510,0.00,8.52,1.24,24.67,50.33
9,10000009,Jen,Ang,12/09/2018,0,845,25350,677.50,348.56,50.70,800,1630,22.58,11.62,1.69,26.67,54.33

In [16]:
Output_csv = Employee_Info_W_Tax_df.to_csv(directory + '/1 Information CSVs/Employee-Information-With-Tax.csv')